### PR TITLE
Add the `pool_id` parameter to Domain::create()

### PR DESCRIPTION
**Pull request by RoyHP**
Fixes https://github.com/mailgun/mailgun-php/issues/788

### CODE REVIEW

**Comment by RoyHP** [comment]
I tested this locally and was able to create a domain in mailgun with the IP pool properly assigned. I know the PR is limited to only the create() method but that's all we needed to configure our domains with the SDK/API.

**Review by DavidGarciaCat — COMMENTED** [review]
Hello @RoyHP 

Thank you for the update!!

Would you mind please adding PHPUnit tests?

Thank you,

**Comment by Pavlico** [comment]
Added tests (didnt succed in adding to same pull request) so can you look at #793

**Comment by Pavlico** [comment]
Merged at #793, thank you

**Pull request closed without merging**
