### PR TITLE
Added Mailbox api usign httpPost etc

### PR DESCRIPTION
**Pull request by Pavlico**

### CODE REVIEW

**Review by DavidGarciaCat — APPROVED** [review]
LGTM - and I love having those tests there - Thanks, @Pavlico

**Comment by Nyholm** [comment]
Awesome!

**Comment by DavidGarciaCat** [comment]
I think this PR has broken something after merging it... https://github.com/mailgun/mailgun-php/actions/runs/1152394628

**Comment by Nyholm** [comment]
Yes. I removed Guzzlehttp/psr7 and this PR was using it. I fixed this in #785

**Comment by DavidGarciaCat** [comment]
Thanks, mate!

**Pull request merged**
