### PR TITLE
Added Event API with pagination

### LINKED ISSUE #188: Create Events API
Includes request dispatcher and any request//response models necessary.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #188 

Do you like the pagination?

```php
$result = $mg->event()->get('domain');
$resultNext = $mg->event()->getPaginationNext($result);
```

Below is an alternative. It does not work as well for someone that does not use the domain objects. And it makes the `EventResponse` a service somehow and not a value object. 
```php
$result = $mg->event()->get('domain');
$resultNext = $result->paginationNext($mg->event());
```

### CODE REVIEW

**Comment by Nyholm** [comment]
I can't really move the trait into a folder named trait. Since PSR0 and PSR4 require the namespace to be the same as folder structure. I can't have "trait" in the namespace because it is a reserved word. Using "traits" violates the idea that namespace always should be singular. 

Also. I do not have a separate folder for classes or interfaces... I'm not a big fan of moving the trait to a subfolder just because it is a trait. :s

**Comment by DavidGarciaCat** [comment]
Understood - in fact we cannot define a `Interfaces` folder for example due the Namespace cannot manage it properly (AFAIK) so when I need to deal with this then I use to add the Interface or Trait keyword at the end, for example `MyAwesomeFileTrait`. Anyway, as I said, up to you! 😄

**Comment by pirogoeth** [comment]
Fantastic! Great work on the pagination part :)

**Comment by Nyholm** [comment]
Tank you for merging

**Pull request merged**
