### PR TITLE
Added Mailgun::ips()

### PR DESCRIPTION
**Pull request by Nyholm**
Note that this PR is to the 2.x branch.

### CODE REVIEW

**Comment by DavidGarciaCat** [comment]
Should this be released as 2.8.1?

**Comment by Nyholm** [comment]
Yes. That seam fair.

**Comment by DavidGarciaCat** [comment]
Merged - however, I think that you already merged some other code that might cause a BC Breaking due to now we're gonna prepare v3?

**Comment by Nyholm** [comment]
Check here: 
screenshot 2019-01-07 at 06 16 03

This PR goes to the 2.x branch. When tagging 2.8.1 we dont do it from master but from the 2.x branch.

**Comment by Nyholm** [comment]
See this https://github.com/mailgun/mailgun-php/compare/2.8.0...2.x

**Pull request merged**
