### PR TITLE
 Add method to get access to Mailing List API endpoints

### PR DESCRIPTION
**Pull request by DavidGarciaCat**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
I released 2.8.1

**Comment by devbranch-vadym** [comment]
Hi @Nyholm,
The 2.8.1 version is not yet available at Packagist, even after 4 hours.
Could this be related? https://twitter.com/seldaek/status/1083667408479576065

Thanks.

**Comment by Nyholm** [comment]
That is probably true. I dont have access. I'll try to ping some admins.

**Comment by Nyholm** [comment]
The tag is on packagist now. Thank you @devbranch-vadym

**Pull request merged**
