### PR TITLE
Fix attachment and inline image renaming

### PR DESCRIPTION
**Pull request by loucou**
As detailed in previous PR, the attachment and inline image new names are expected to be associated to the 'filename' key by Message.php

### CODE REVIEW

**Comment by DavidGarciaCat** [comment]
https://github.com/mailgun/mailgun-php/pull/567

**Comment by loucou** [comment]
Here the example:
In the final email, the file is named hello.txt with this PR, otherwise it stays 'my_file.txt'

$builder = new \Mailgun\Message\MessageBuilder();
$builder->setFromAddress(...);
$builder->addToRecipient(...);
$builder->setSubject('example');
$builder->setTextBody('Hello world');

file_put_contents('my_file.txt', 'foobar');
$builder->addAttachment('my_file.txt', 'hello.txt');

$mg = \Mailgun\Mailgun::create('...', 'https://api.eu.mailgun.net');
$mg->messages()->send('mg.avisvideo.io', $builder->getMessage());

regards

**Comment by Nyholm** [comment]
I think this looks good. I need to do a careful review to better understand the difference

**Comment by Nyholm** [comment]
I cannot find any official docs that supports this... Hm.

**Comment by kokoshneta** [comment]
Not sure if this is actually related to this or not, but when the file name contains non-ASCII characters, it ends up getting modified somewhat randomly when delivered. In the logs available in the Mailgun dashboard, the name appears correctly, but in the actual e-mail, it is altered. See [this StackOverflow question](https://stackoverflow.com/questions/55108056/mailgun-randomly-renames-attachments) I just asked for more details.

Is this definitely something on Mailgun’s end, or might the library somehow have a fixable effect on it?

**Comment by Nyholm** [comment]
I finally got around to test this. Thank you!

**Comment by loucou** [comment]
Cool, thanks!

**Comment by zincchuang** [comment]
Will this fix be introduced in version 2.8 above? Currently we are using PHP5.6 and version 3.0.0-Beta requires PHP7 which is a problem to us now.

**Comment by kuoliangkwong** [comment]
Hi thanks for the fix. Is it going to be available for composer mailgun ^2.8? I'm using 2.8.1 composer version but the fix is not there yet

**Pull request merged**
