### PR TITLE
Force dkim authority

### PR DESCRIPTION
**Pull request by Tiboonn**
Added support for the force_dkim_authority parameter when adding/creating a new Mailgun domain.

### CODE REVIEW

**Comment by Tiboonn** [comment]
@DavidGarciaCat Noticed you reviewed a lot of pull request in this repo. Could you please review these changes?

**Comment by Tiboonn** [comment]
Hi @DavidGarciaCat 

I noticed the CI failing. But I looked at it and dont think it got introduced in my code changes.
I also noticed this PR
https://github.com/mailgun/mailgun-php/pull/676
This looks to fix the issues with phpstan. Not sure if that would fix my PR though.

Cheers

**Comment by DavidGarciaCat** [comment]
> I also noticed this PR
> #676

Nice! I didn't realise about this one. It's now merged and I'm rebuilding your branch so if all works then consider it merged

**Comment by DavidGarciaCat** [comment]
Thanks - I'll send another PR soon with the CI fixes

**Comment by Tiboonn** [comment]
@DavidGarciaCat Thanks a lot!! :)

**Pull request merged**
