### PR TITLE
Renamed namespace from Resource\Api to Model

### PR DESCRIPTION
**Pull request by MichalHanajik**
Renamed all sources of **Resource\Api** to **Model** in all files as mentioned in #289

### CODE REVIEW

**Comment by MichalHanajik** [comment]
Of course I can, I was not sure if this is already as part of Models in this case.
Should I update already all models final from #288  ?

**Comment by Nyholm** [comment]
Sure. Let's. But do not solve any more issues in this PR. Fixing #288 and #289 in this PR is enough.

**Comment by Nyholm** [comment]
Also, when making "all models final" you have to be aware that some models cannot be marked final because another model extends that one.

**Comment by MichalHanajik** [comment]
Added final for classes. Should be alright.

**Comment by Nyholm** [comment]
Awesome. Just fix the minor style issue and I'll be happy to merge

**Comment by MichalHanajik** [comment]
Fixed :)

**Comment by Nyholm** [comment]
Thanks

**Pull request merged**
