### PR TITLE
Make sure we dont inherit final classes.

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
WIP

**Comment by Nyholm** [comment]
Ready for review.

**Comment by DavidGarciaCat** [comment]
Not final or abstract - are we sure about this?

**Comment by Nyholm** [comment]
We use those classes. That is why :/

**Comment by DavidGarciaCat** [comment]
I was thinking about being consistent, that's all

**Comment by Nyholm** [comment]
> I was thinking about being consistent, that's all

True. We could remote `ShowResponse` and just let the API return just return this model instead. 
OR, we could do some weird things with traits... This is actually the most simple solution, but im not sure it is the best. 

Lets revisit before tagging 3.0. I will merge now because the build is currently broken.

**Pull request merged**
