### PR TITLE
Added response classes

### PR DESCRIPTION
**Pull request by Nyholm**
This will address some issues in #186 

Is this something we want to do?
There is a lot of objects created. Should we consider performance here? Should we have a way to opt-out of this feature?

### CODE REVIEW

**Comment by DavidGarciaCat** [comment]
❓ Question: What do you think about update the `AllResponse` class to `abstract class`? We can set a new class for each response type but keeping this process available, and - at the same time - we won't allow to transform from an Array just some fields instead of all of them.

**Comment by Nyholm** [comment]
The name `AllResponse` is pretty bad. It should reflect the "Response" for the `Stats::all()` function. Just tile `TotalResponse` is for `Stats::total()`.

>  we won't allow to transform from an Array just some fields instead of all of them.

I do not understand. Can you elaborate?

**Comment by DavidGarciaCat** [comment]
Sure,

What I am suggesting is to transform the `AllResponse` object to be an abstract like:
```
namespace Mailgun\Resource\Api\Stats;

abstract class AbstractResponse
{
    public static function createFromArray(array $array)
    {
        // some code here (shared fields)
        return $object;
    }
}
```

And then build a Response for each type, like:
```
namespace Mailgun\Resource\Api\Stats;

final class TotalResponse extends AbstractResponse
{
    public static function createFromArray(array $array)
    {
        $object = parent::createFromArray($array);
        // some code here (custom fields)
        return $object;
    }
}
```

**Comment by Nyholm** [comment]
That would be good, but (as far as I can see) there is not shared fields. Just consider these two stats responses. They share nothing...

**Comment by Nyholm** [comment]
I like this direction. Im going to merge it into my other PR.

**Pull request merged**
