### PR TITLE
Bump year updating Copyright

### PR DESCRIPTION
**Pull request by shakaran**
This could be easily achieved in next years with the following bash command and changing the years:

`grep -l "2013-2016" | xargs sed -i 's/2013-2016/2013-2017/g'`

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. But this is controlled by style CI. I have a task for admin (@pirogoeth) to update the StyleCI settings for file headers: https://github.com/mailgun/mailgun-php/issues/343

**Comment by shakaran** [comment]
@Nyholm since style CI is not supported with php-cs-fixer 2.x versions, StyleCI still will control this? Even if controlled or not, it needs to be updated properly, so I think that the ideal should be merge or at least upgrade .php_cs to use php-cs-fixer 2.x and update the headers

**Comment by DavidGarciaCat** [comment]
Hey @shakaran - What @Nyholm means is this repository is inspected by Style CI when new commits are pushed, and the PHP headers that contain the years are part of the Style CI settings, so there's no need to apply this PR.

**Comment by shakaran** [comment]
@DavidGarciaCat but since Style CI is not working(because not support for PHP-CS-Fixer 2.x branch) (or at least is not commiting and updating in old files), it never gets updated or I am wrong with that statment?

**Comment by DavidGarciaCat** [comment]
Hey @shakaran - As @Nyholm said, issue https://github.com/mailgun/mailgun-php/issues/343 is related, and he has sent already a reminder to @pirogoeth via [Gitter](https://gitter.im/mailgun/mailgun-php), asking if he can deal with this request, so there is no need to keep this PR here.

**Pull request closed without merging**
