### PR TITLE
Do not validate API responses. Create Response objects that have part…

### PR DESCRIPTION
**Pull request by Nyholm**
…ial data instead

Fix issue #225

### CODE REVIEW

**Comment by Nyholm** [comment]
Can I get any feedback on this?

**Comment by Nyholm** [comment]
This PR removes validation of server responses. We did not test these validations before, that's why the tests are unchanged. 

@pirogoeth, are you okey with merging this?

**Comment by pirogoeth** [comment]
I will merge this, but at this point, I believe we should just drop the resource half of our domain-resource paradigm. We should keep this simple - provide a wrapper for users to use to access the API with clean calls, receive clean, untouched JSON output back from the API. No trying to load it in to objects, no validation. If anything, we can provide some utility helpers that will help with common API tasks (pagination, fetching from a links blocks, fetching stored message from the correct API endpoint, etc).

------

Realistically, if we are not going to validate server responses, then we have no need for multiple response classes. If anything we could have one response class containing the pagination common code as well as a \stdClass member (the JSON-decoded response). This makes consuming data from the API easier for the users and ensures that we don't accidentally "protecting" the users from using their data the way they want to.

**Comment by Nyholm** [comment]
We talked about this. I can't find the issue though. 

I created an example in the readme (#240) to show how you can get this clean array/json output if you want. 

What makes the consuming of the API easier is a matter of taste. Ask any Java developer and he/she will always say that one should use objects. A python developer on the other hand would prefer primary types instead. PHP is somewhere in between. 

If we could serve one APIResponse that would be great. But the API is not build that way.

**Pull request merged**
