### PR TITLE
Disable integration tests until they are improved

### PR DESCRIPTION
**Pull request by Nyholm**
Until #235 is resolved.

### CODE REVIEW

**Comment by Nyholm** [comment]
Haha agreed. But I want to disable them in to make travis test green. Othewise only admin can merge PRs until #235 is resolved..

Example, I would like to merge this: https://github.com/mailgun/mailgun-php/pull/238

**Comment by DavidGarciaCat** [comment]
Why to disable these tests instead of fix the ones that are failing? Please don't misunderstand me, I know what you mean, but from my POV we can improve the tests later, however ignore a known error is not good. Fortunately Mailgun sends emails, but what happen if we work with money? Are you going to ignore that test? :)

**Comment by Nyholm** [comment]
The test was just recently added. Then we did a refactoring and the test broke. It is not the code that is broken but the tests. 
Since I cannot properly run the locally I have a hard time fixing them right now. (More described in #235) 

If the tests are not fixed or disabled I can no longer push anything to this repo because of the current "protection settings".

**Comment by DavidGarciaCat** [comment]
Up to you - As I said on PR #235 best practices suggest to write test first to prevent unexpected behaviours, and here I described the example (car wheels), so if @pirogoeth is happy with this update, then feel free to merge 😄 - @pirogoeth ?

**Comment by pirogoeth** [comment]
I've got no problems with disabling the integration tests for now. If this was a stable release of the bindings, that's one thing, but this is under active development in a not even nearly stable phase. And, it's not like they're going to be disabled forever, just long enough to fix the tests.

**Pull request merged**
