### PR TITLE
Mailgun #417 Interfaces names should end with "Interface"

### PR DESCRIPTION
**Pull request by DavidGarciaCat**
As per my own inspection running SensioLabs Insight:
An `Interface` file should end with `Interface` for better clarity.

This PR should fix https://github.com/mailgun/mailgun-php/issues/417

### CODE REVIEW

**Comment by Nyholm** [comment]
This is symfony coding standards. It is not part of PSR2. 

This is a BC breaking change. If this is merged the next version has to be 3.0.

**Comment by DavidGarciaCat** [comment]
Not a problem! ;-)

**Comment by Nyholm** [comment]
I've reviewed the PR and I think it looks good. 

However, since merging this PR will break BC we should ask ourselves: "Is this PR worth releasing 3.0 over?". I do not think so, but I would love to merge this when the arguments for 3.0 becomes stronger. 

We should create a better roadmap. There are a few things that need to be done. On the top of my head: BatchMessages and documentation.

**Comment by DavidGarciaCat** [comment]
Hey @Nyholm as I said on my last message, "not a problem", so happy to discuss potential changes for the v3 roadmap. By other side, I still need to work on the Email Validator update, hope to do it soon, I think I'll have some time next days

**Comment by TemirkhanN** [comment]
@DavidGarciaCat since it breaks backward compatibility and you still need it badly I suggest to make steps iterably keeping backward compatibility. Kind of

```PHP

interface HydratorInterface extends Hydrator {}

/**
 * @deprecated will be removed in 3.0.0
 */
interface Hydrator {...}
```

**Comment by DavidGarciaCat** [comment]
Hy @TemirkhanN 

Don't worry for the BC, as @Nyholm pointed this PR can be merged as part of the v3 SDK, a new major version means that we might break BC due the removal of deprecated code or the implementation of other changes like - like this one.

Best,

**Comment by DavidGarciaCat** [comment]
As pointed out [here](https://github.com/mailgun/mailgun-php/pull/418#issuecomment-348885125), this is `This is symfony coding standards` so I believe that we can close this PR for now. Let's discuss if we really need this or not.

**Pull request closed without merging**
