### PR TITLE
Make sure we do not instantiate an abstract class.

### PR DESCRIPTION
**Pull request by Nyholm**
Fixed minor bug introduced in #420. 

FYI @Eugst, We missed this in the review.

### CODE REVIEW

**Comment by Eugst** [comment]
yay... Sorry, my bad... I forgot to push :) it was in a second commit... 
thanks for cleanup! strange that tests didn't caught it.

**Comment by Nyholm** [comment]
No worries at all. Both me and David missed it. I'll tag this fix in a new release now. 

Thank you

**Comment by DavidGarciaCat** [comment]
Nice catch @Nyholm - We'll need to pay more atention

**Comment by Nyholm** [comment]
No worries, That is why we have tests. =)

**Pull request merged**
