### PR TITLE
Fixed missing mailinglist

### PR DESCRIPTION
**Pull request by fragkp**
I've added the missing `mailingList` method 😄 

Also, I sorted all api methods by name - hope it's ok.

### CODE REVIEW

**Comment by DavidGarciaCat** [comment]
Thanks @fragkp 

@Nyholm unless you have an objection, I'll merge this one later today

**Comment by DavidGarciaCat** [comment]
I guess this is the answer?

> Also, I sorted all api methods by name - hope it's ok.

**Comment by Nyholm** [comment]
Yeah. David, can you double check that nothing was accidentally removed?

Sorting like this is fine. But it makes the PR harder to review. It would be easier if you made two PRs. 

I’m currently on vacation. I found a bus stop with “some” WiFi. If David thinks this is fine I’ll be happy to see it merged.

**Comment by DavidGarciaCat** [comment]
> Sorting like this is fine. But it makes the PR harder to review. It would be easier if you made two PRs.

I agree - and I can double check all the methods before merging, indeed.

> I’m currently on vacation. I found a bus stop with “some” WiFi. If David thinks this is fine I’ll be happy to see it merged.

Enjoy !! And keep away your inbox !! 🍹

**Pull request merged**
