### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by clhammer**
Add license + license info to composer.json

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. We do need a license file. Though, you cannot change the license of an open source project like this. It violates the current license. You need permissions from every contributor. 

Also, why would you change the license to Apache2? I do not see a case where many patents will come out of this project.

**Comment by clhammer** [comment]
Nyholm,

It's my understanding that this wouldn't be a violation as there isn't any actual license declared, just a mention of it in the composer.json meta-data.

Also, I changed it to Apache2 as a move to have license standardization across our SDK's.

**Comment by Nyholm** [comment]
Just because it was a poor license declaration (missing license file and license in the file headers) doesn't mean that there were no license at all. 

Having the same license on all your SDKs makes sense. But why Apache2?

**Comment by Nyholm** [comment]
It has been a while since this PR was updated. 
I suggest closing it in favor for #163. @clhammer what do you think?

**Comment by Nyholm** [comment]
Bump @clhammer

**Comment by Nyholm** [comment]
Closed by #163

**Pull request closed without merging**
