### PR TITLE
Bump RestClient default API version to 'v3'

### PR DESCRIPTION
**Pull request by pirogoeth**
Fixes up #182.

### CODE REVIEW

**Comment by Nyholm** [comment]
Is this the only change that is needed? Is v3 backwards compatible with v2? Would this require a new major version?

**Comment by pirogoeth** [comment]
~~According to the tests, everything still works but I will verify tomorrow.~~

So it appears we can't rely on tests to tell us if this change will break everything. Should probably manually verify that this isn't breaking *everything* or increase test coverage overall...

----------------------------
```
Code Coverage Report:      
  2016-10-13 20:19:49      
                           
 Summary:                  
  Classes: 68.75% (11/16)  
  Methods: 44.44% (28/63)  
  Lines:   71.83% (255/355)

\Mailgun::Mailgun
  Methods:  50.00% ( 6/12)   Lines:  71.43% ( 25/ 35)
\Mailgun\Connection::RestClient
  Methods:  14.29% ( 2/14)   Lines:  50.48% ( 53/105)
\Mailgun\Lists::OptInHandler
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 13/ 13)
\Mailgun\Messages::BatchMessage
  Methods:  80.00% ( 4/ 5)   Lines:  94.23% ( 49/ 52)
\Mailgun\Messages::MessageBuilder
  Methods:  51.85% (14/27)   Lines:  82.73% (115/139)
```

**Comment by Nyholm** [comment]
True. I do not think any test is using the API server.

**Comment by Nyholm** [comment]
FYI: https://github.com/mailgun/mailgun-php/pull/129

**Comment by DavidGarciaCat** [comment]
👍 Thanks @Nyholm for that other PR - looks like this one does not make sense if some API endpoints are not providing v3 support

**Comment by Nyholm** [comment]
Yes, I'll close this PR for now.

**Pull request closed without merging**
