### PR TITLE
Updated to Guzzle5

### PR DESCRIPTION
**Pull request by Nyholm**
Guzzle5 and some other neat tricks makes the `RestClient` a lot cleaner. 

This PR does not change the API nor does it add any features. I think this is a necessary update because it reduces the number of dependencies in my application. I don't want dependencies on both Guzzle3 and Guzzle5. 

Also, with the new Guzzle we do no longer suffer from the bug temporarily fixed [here](https://github.com/mailgun/mailgun-php/commit/8d23a5bb9f36db8594836329b3905d0dfb137da7)

### CODE REVIEW

**Comment by Nyholm** [comment]
This PR resolve issue #73

**Comment by Nyholm** [comment]
Any updates on this?

**Comment by Nyholm** [comment]
Rebased. Ping @jessespears.

**Comment by jessespears** [comment]
Thanks for the contribution and sorry about the long wait!  Please send an email to me at jesse@mailgun.com with your info so we can send you a Mailgun t-shirt.

**Comment by Nyholm** [comment]
Thank you for merging this. I'm happy to contribute to make this project better. 

PS, don't forget to close #73

**Comment by Nyholm** [comment]
When can we expect version 1.8.0 to be tagged?

**Comment by jessespears** [comment]
Today =)

**Comment by Nyholm** [comment]
You are awesome @jessespears!

**Comment by jessespears** [comment]
Thanks for waiting, version 1.8 is tagged!  You are awesome @Nyholm!

**Comment by afrowuk** [comment]
Will there be an update to Guzzle6?

**Comment by auro1** [comment]
#86

**Pull request merged**
