### PR TITLE
Message\ShowResponse set empty array when no message headers key

### PR DESCRIPTION
**Pull request by ixarlie**
This PR resolves an issue when a `Message\ShowResponse` is created and the argument `$data` does not have a `message-headers` key.

`public function getMessageHeaders(): array`

In that case, making use of `getMessageHeaders` a TypeError is thrown.

> Return value of Mailgun\Model\Message\ShowResponse::getMessageHeaders() must be of the type array, null returned

Using the same approach from the "attachments" property.

### CODE REVIEW

**Review by DavidGarciaCat — APPROVED** [review]
Nice catch!

**Comment by Pavlico** [comment]
@ixarlie hi can you fix composer issue, its simple change in composer.json file

**Comment by ixarlie** [comment]
> @ixarlie hi can you fix composer issue, its simple change in composer.json file

I'm sorry @Pavlico , not sure what kind of fix you mean. Looking at the composer.json file but no idea what to do.
If you can give me some directions. Thanks!

**Comment by Pavlico** [comment]
We cool, I think you have old composer on your branch that doesn't pass this check, update your local master with current version and then merge it into your branch and it will fix it, I think :) or if you don't want to update master just copy current composer.json file to your branch, you can see details on how your composer.json file is different in composer normalise check

**Comment by ixarlie** [comment]
@Pavlico that worked! Thank you!

**Comment by Pavlico** [comment]
Thanks to you too ! :)

**Pull request merged**
