### PR TITLE
Add new package in Framework integration section

### PR DESCRIPTION
**Pull request by narendravaghela**
I have created a plugin for CakePHP to send emails using Mailgun SDK and added the reference to package in readme file.

### CODE REVIEW

**Comment by narendravaghela** [comment]
Hello there,
Is there any possibility to merge this request?

**Comment by Nyholm** [comment]
Your library has in total 10 installs. I would prefer a more commonly used integration. There are cakePHP integrations with far more installation than yours. 

If it was up to me I would be happy to include your library when it has gotten some attraction.

**Comment by narendravaghela** [comment]
Thank you for reply.
If you can add this to list, It would be helpful to get some attraction to this lib. Anyways, not a problem, let's wait until my library gets some more users.

**Comment by Nyholm** [comment]
Yes, lets wait a while.

**Pull request closed without merging**
